server:
  port: 9092
spring:
  application:
    name: Myshopping
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
  instance:
    hostname: localhost 

 
 